/*
 * Oldalbeallitas_dlg.java
 *
 * Created on 2005. április 15., 18:58
 */

package hu.wfs.vonalkod.gui.oldalbeallitas;

import hu.wfs.vonalkod.modell.Oldalbeallitas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author  Béci
 */
public class Oldalbeallitas_dlg extends javax.swing.JDialog implements ActionListener {
	
	public static final int BEZÁRÁSIOPCIÓ_OK=1;
	private int bezárásiOpció=-1;
	
	private Oldalbeallitas_tlp panel;
	
	private final static int MIN_ABL_MAG=490;
	private final static int MIN_ABL_SZEL=467;
	
	/** Creates new form Oldalbeallitas_dlg */
	public Oldalbeallitas_dlg(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		panel=new Oldalbeallitas_tlp();
		panel.addActionListener(this);
		getContentPane().add(panel);
		addComponentListener(new ComponentAdapter(){
			public void componentResized(ComponentEvent e) {
				int szel=getWidth();
				int mag=getHeight();
				if (getWidth()<MIN_ABL_SZEL)
					szel=MIN_ABL_SZEL;
				if (getHeight()<MIN_ABL_MAG)
					mag=MIN_ABL_MAG;
				setSize(szel, mag);
			}
		});
		setSize(MIN_ABL_SZEL, MIN_ABL_MAG);
	}

	public void actionPerformed(ActionEvent e) {
		if (e.getActionCommand().equalsIgnoreCase("Rendben"))
			bezárásiOpció=BEZÁRÁSIOPCIÓ_OK;
		setVisible(false);
		dispose();
	}
	
	public void setOldalbeállítás(Oldalbeallitas oldalbeállítás) {
		panel.setOldalbeállítás(oldalbeállítás);
	}		
	
	public Oldalbeallitas getOldalbeállítás()  {
		return panel.getOldalbeállítás();
	}	
	
	public int showDialógus() {
		super.show();
		return bezárásiOpció;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-END:initComponents
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Oldalbeallitas_dlg(new javax.swing.JFrame(), true).setVisible(true);
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	
}
