/*
 * AllapotjelzoDialogus.java
 *
 * Created on 2004. szeptember 27., 17:34
 */

package hu.wfs.vonalkod.shared;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  Rendszergazda
 */
public class AllapotjelzoDialogus extends javax.swing.JDialog {
	Component szülõAblak;
	
	/** Creates new form AllapotjelzoDialogus */
	public AllapotjelzoDialogus(Component szülõAblak) {
		super(JOptionPane.getFrameForComponent(szülõAblak), true);
		this.szülõAblak=szülõAblak;
		initComponents();
		setSize(350,25);		
	}
	
	public void show() {
		setLocationRelativeTo(szülõAblak);
		super.show();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        pb = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("\u00c1llapotjelz\u0151");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setEnabled(false);
        setResizable(false);
        setUndecorated(true);
        pb.setIndeterminate(true);
        pb.setString("");
        pb.setStringPainted(true);
        getContentPane().add(pb, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
	
	
	public void setSzöveg(String s) {
		pb.setString(s);
	}
	
	/**
	 * Alapbeállításként a szöveg kijelzésre kerül
	 */
	public void setSzövegKijelzés(boolean b) {
		pb.setStringPainted(b);
	}
	
	public void bezárás() {
		setVisible(false);
		dispose();
	}
}
